# outage_detection 
## problem statement - we have to help the company predict outage duration .

# Importing our necessary libraries 

In [1]:
import pandas as pd
import numpy as np
import os


# Visualization libraries.
import matplotlib as plt
import matplotlib.pyplot as plt
import seaborn as sns

# Lets begin with Exploratory Data Analysis

In [4]:
df1 = pd.read_csv('broadband_data.csv')

In [5]:
df2 = pd.read_csv('report_data.csv')

In [6]:
df3 = pd.read_csv('server_data.csv')

In [7]:
df4 = pd.read_csv('outage_data.csv')

In [8]:
df5 = pd.read_csv('train_data.csv')

In [9]:
test = pd.read_csv('test_data.csv')
test.head()

id area_code
0   3340  area_344
1  14067  area_933
2   1134   area_16
3     27  area_793
4   9793  area_344

In [10]:
test1 = test["id"]
test1.head()

0     3340
1    14067
2     1134
3       27
4     9793
Name: id, dtype: int64

## Merging the Dataframes 

In [11]:
df6 =pd.merge(df2,df1,on = "id", how ='left')

In [12]:
df7 = pd.merge(df3,df4,on="id",how = 'left')

In [13]:
df8 = pd.merge(df6,df7,on ="id", how = 'left')

In [14]:
data = pd.merge(df8,df5,on = "id")
data.shape

(48973, 8)

In [15]:
test.shape

(1477, 2)

In [16]:
test_data = pd.merge(data,test, on = "area_code", how = 'right')
test_data.shape

(237264, 9)

In [17]:
test_data.head(10)

id_x      log_report_type  volume    broadband_type  \
0  8011.0   log_report_type_68     7.0  broadband_type_8   
1  2588.0   log_report_type_82     9.0  broadband_type_8   
2  2588.0   log_report_type_82     9.0  broadband_type_8   
3  2588.0  log_report_type_201     5.0  broadband_type_8   
4  2588.0  log_report_type_201     5.0  broadband_type_8   
5  2588.0   log_report_type_80    15.0  broadband_type_8   
6  2588.0   log_report_type_80    15.0  broadband_type_8   
7  2588.0  log_report_type_203     5.0  broadband_type_8   
8  2588.0  log_report_type_203     5.0  broadband_type_8   
9  4848.0   log_report_type_56     3.0  broadband_type_8   

      transit_server_type    outage_type area_code  outage_duration  id_y  
0  transit_server_type_15  outage_type_2    area_1              0.0  8148  
1  transit_server_type_15  outage_type_1    area_1              0.0  8148  
2  transit_server_type_11  outage_type_1    area_1              0.0  8148  
3  transit_server_type_15  outage_type_1    area_1              0.0  8148  
4  transit_server_type_11  outage_type_1    area_1              0.0  8148  
5  transit_server_type_15  outage_type_1    area_1              0.0  8148  
6  transit_server_type_11  outage_type_1    area_1              0.0  8148  
7  transit_server_type_15  outage_type_1    area_1              0.0  8148  
8  transit_server_type_11  outage_type_1    area_1              0.0  8148  
9  transit_server_type_11  outage_type_1    area_1              0.0  8148

In [21]:
test_data['id_y'].nunique()


1477

In [22]:
data.isna().sum()

id                     0
log_report_type        0
volume                 0
broadband_type         0
transit_server_type    0
outage_type            0
area_code              0
outage_duration        0
dtype: int64

In [23]:
test_data.isna().sum()

id_x                   63
log_report_type        63
volume                 63
broadband_type         63
transit_server_type    63
outage_type            63
area_code               0
outage_duration        63
id_y                    0
dtype: int64

In [24]:
test1.dtype

dtype('int64')

In [25]:
test_data.drop(['id_x'],axis = 1 , inplace = True)

In [26]:
test_data.drop(['outage_duration'], axis = 1 ,inplace= True)

In [27]:
test_data.shape

(237264, 7)

### checking for na values 

In [24]:
print("Total number of rows: " + str(len(data.index)))
print("Number of  na values:")
for column in data.columns:
    print(" * " + column + ": " + str(data[column].isnull().sum()))

Total number of rows: 48973
Number of  na values:
 * id: 0
 * log_report_type: 0
 * volume: 0
 * broadband_type: 0
 * transit_server_type: 0
 * outage_type: 0
 * area_code: 0
 * outage_duration: 0


In [25]:
print("Total number of rows: " + str(len(test_data.index)))
print("Number of  na values:")
for column in test_data.columns:
    print(" * " + column + ": " + str(test_data[column].isnull().sum()))

Total number of rows: 237264
Number of  na values:
 * log_report_type: 63
 * volume: 63
 * broadband_type: 63
 * transit_server_type: 63
 * outage_type: 63
 * area_code: 0
 * id_y: 0


In [28]:
data.shape

(48973, 8)

In [29]:
test_data.dtypes

log_report_type         object
volume                 float64
broadband_type          object
transit_server_type     object
outage_type             object
area_code               object
id_y                     int64
dtype: object

In [30]:
data.describe()

id        volume  outage_duration
count  48973.000000  48973.000000     48973.000000
mean    9141.189084      8.605742         0.539889
std     5390.273600     23.487812         0.725738
min        1.000000      1.000000         0.000000
25%     4493.000000      1.000000         0.000000
50%     9107.000000      2.000000         0.000000
75%    13663.000000      6.000000         1.000000
max    18550.000000    877.000000         2.000000

In [31]:
test_data.describe()

volume           id_y
count  237201.000000  237264.000000
mean       11.441642    9034.102637
std        25.632849    5520.130038
min         1.000000       8.000000
25%         1.000000    4231.000000
50%         3.000000    8770.000000
75%        10.000000   13814.000000
max       877.000000   18539.000000

In [32]:
data.nunique()


id                     5904
log_report_type         310
volume                  240
broadband_type           10
transit_server_type      49
outage_type               5
area_code               876
outage_duration           3
dtype: int64

In [33]:
test_data.nunique()

log_report_type         272
volume                  238
broadband_type           10
transit_server_type      47
outage_type               4
area_code               531
id_y                   1477
dtype: int64

In [34]:
datadp = data[data.duplicated()]
datadp.head()

Empty DataFrame
Columns: [id, log_report_type, volume, broadband_type, transit_server_type, outage_type, area_code, outage_duration]
Index: []

In [35]:
test_datadp = test_data[test_data.duplicated()]
test_datadp

log_report_type  volume    broadband_type     transit_server_type  \
31      log_report_type_172     2.0  broadband_type_8  transit_server_type_11   
32      log_report_type_172     2.0  broadband_type_8  transit_server_type_15   
51      log_report_type_201     2.0  broadband_type_8  transit_server_type_15   
52      log_report_type_201     2.0  broadband_type_8  transit_server_type_11   
58      log_report_type_201     5.0  broadband_type_8  transit_server_type_11   
64       log_report_type_82     2.0  broadband_type_8  transit_server_type_15   
65       log_report_type_82     2.0  broadband_type_8  transit_server_type_11   
70       log_report_type_56     1.0  broadband_type_8  transit_server_type_15   
71       log_report_type_56     1.0  broadband_type_8  transit_server_type_11   
104     log_report_type_201     2.0  broadband_type_8  transit_server_type_11   
105     log_report_type_201     2.0  broadband_type_8  transit_server_type_15   
106      log_report_type_82     2.0  broadband_type_8  transit_server_type_11   
107      log_report_type_82     2.0  broadband_type_8  transit_server_type_15   
108      log_report_type_80     2.0  broadband_type_8  transit_server_type_11   
109      log_report_type_80     2.0  broadband_type_8  transit_server_type_15   
124      log_report_type_56     1.0  broadband_type_8  transit_server_type_11   
125      log_report_type_56     1.0  broadband_type_8  transit_server_type_15   
128      log_report_type_80     2.0  broadband_type_8  transit_server_type_11   
129      log_report_type_80     2.0  broadband_type_8  transit_server_type_15   
130     log_report_type_203     5.0  broadband_type_8  transit_server_type_11   
131     log_report_type_203     5.0  broadband_type_8  transit_server_type_15   
132     log_report_type_201     1.0  broadband_type_8  transit_server_type_11   
133     log_report_type_201     1.0  broadband_type_8  transit_server_type_15   
134     log_report_type_172     2.0  broadband_type_8  transit_server_type_15   
135     log_report_type_172     2.0  broadband_type_8  transit_server_type_11   
142      log_report_type_80     1.0  broadband_type_8  transit_server_type_15   
143      log_report_type_80     1.0  broadband_type_8  transit_server_type_11   
147      log_report_type_80     1.0  broadband_type_8  transit_server_type_15   
148     log_report_type_201     1.0  broadband_type_8  transit_server_type_15   
180     log_report_type_172     2.0  broadband_type_8  transit_server_type_11   
...                     ...     ...               ...                     ...   
237115   log_report_type_71     5.0  broadband_type_8  transit_server_type_11   
237116  log_report_type_203     2.0  broadband_type_8  transit_server_type_15   
237117  log_report_type_203     2.0  broadband_type_8  transit_server_type_11   
237124   log_report_type_82     8.0  broadband_type_8  transit_server_type_15   
237125   log_report_type_82     8.0  broadband_type_8  transit_server_type_11   
237126  log_report_type_193     1.0  broadband_type_8  transit_server_type_15   
237127  log_report_type_193     1.0  broadband_type_8  transit_server_type_11   
237128   log_report_type_71     2.0  broadband_type_8  transit_server_type_15   
237129   log_report_type_71     2.0  broadband_type_8  transit_server_type_11   
237130  log_report_type_203     2.0  broadband_type_8  transit_server_type_15   
237131  log_report_type_203     2.0  broadband_type_8  transit_server_type_11   
237134   log_report_type_82     6.0  broadband_type_8  transit_server_type_11   
237135   log_report_type_82     6.0  broadband_type_8  transit_server_type_15   
237138  log_report_type_193     4.0  broadband_type_8  transit_server_type_11   
237139  log_report_type_193     4.0  broadband_type_8  transit_server_type_15   
237140   log_report_type_71     3.0  broadband_type_8  transit_server_type_11   
237141   log_report_type_71     3.0  broadband_type_8  transit_server_type_15   
237142  log_report_type_203     6.0  broadb

In [36]:
test_data.drop_duplicates(subset = "id_y", inplace = True)

In [37]:
test_data.shape

(1477, 7)

In [38]:
test_data["id_y"].shape

(1477,)

In [77]:
data.dtypes

id                     int64
log_report_type        int16
volume                 int64
broadband_type         int64
transit_server_type    int64
outage_type            int64
area_code              int16
outage_duration        int64
dtype: object

In [91]:
data.dtypes

id                     int64
log_report_type        int16
volume                 int64
broadband_type         int64
transit_server_type    int64
outage_type            int64
area_code              int16
outage_duration        int64
dtype: object

In [75]:
data.log_report_type = data.log_report_type.astype("category").cat.codes

In [86]:
test_data.outage_type.fillna(test_data.outage_type.mean(),inplace=True)


In [76]:
data.area_code = data.area_code.astype("category").cat.codes

In [71]:
test_data.log_report_type = test_data.log_report_type.astype("category").cat.codes

In [41]:
from sklearn.preprocessing import LabelEncoder
from sklearn import preprocessing
label_encoder = preprocessing.LabelEncoder() 
data['broadband_type']= label_encoder.fit_transform(data['broadband_type']) 
print(data.head())

     id      log_report_type  volume  broadband_type     transit_server_type  \
0  8011   log_report_type_68       7               8  transit_server_type_15   
1  2588   log_report_type_82       9               8  transit_server_type_15   
2  2588   log_report_type_82       9               8  transit_server_type_11   
3  2588  log_report_type_201       5               8  transit_server_type_15   
4  2588  log_report_type_201       5               8  transit_server_type_11   

     outage_type area_code  outage_duration  
0  outage_type_2    area_1                0  
1  outage_type_1    area_1                0  
2  outage_type_1    area_1                0  
3  outage_type_1    area_1                0  
4  outage_type_1    area_1                0  


### no duplicate values found 

## Mapping few categorical features so it heps in visualization.

In [64]:
data.outage_type=data.outage_type.map({'outage_type_1':1,'outage_type_2':2,'outage_type_3':3,'outage_type_4': 4 , 'outage_type_5':5})

In [65]:
test_data.outage_type=test_data.outage_type.map({'outage_type_1':1,'outage_type_2':2,'outage_type_3':3,'outage_type_4': 4 , 'outage_type_5':5})

In [66]:
data.broadband_type=data.broadband_type.map({'broadband_type_1':1,'broadband_type_2':2,'broadband_type_3':3,'broadband_type_4': 4 , 'broadband_type_5':5, 'broadband_type_6':6, 'broadband_type_7':7, 'broadband_type_8':8, 'broadband_type_9':9, 'broadband_type_10':10})

In [67]:
test_data.broadband_type=test_data.broadband_type.map({'broadband_type_1':1,'broadband_type_2':2,'broadband_type_3':3,'broadband_type_4': 4 , 'broadband_type_5':5, 'broadband_type_6':6, 'broadband_type_7':7, 'broadband_type_8':8, 'broadband_type_9':9, 'broadband_type_10':10})

In [68]:
data.transit_server_type=data.transit_server_type.map({'transit_server_type_1':1,'transit_server_type_2':2,'transit_server_type_3':3,'transit_server_type_5':5,'transit_server_type_6':6,'transit_server_type_7':7,'transit_server_type_8':8,'transit_server_type_9':9,'transit_server_type_10':10,'transit_server_type_11':11,'transit_server_type_12':12,'transit_server_type_13':13,'transit_server_type_14':14,'transit_server_type_15':15,'transit_server_type_18':18,'transit_server_type_19':19,'transit_server_type_20':20,'transit_server_type_21':21,'transit_server_type_22':22,'transit_server_type_23':23,'transit_server_type_24':24,'transit_server_type_25':25,'transit_server_type_26':26,'transit_server_type_27':27,'transit_server_type_28':28,'transit_server_type_29':29,'transit_server_type_30':30,'transit_server_type_31':31,'transit_server_type_32':32,'transit_server_type_34':34,'transit_server_type_35':35,'transit_server_type_36':36,'transit_server_type_37':37,'transit_server_type_38':38,'transit_server_type_39':39,'transit_server_type_40':40,'transit_server_type_41':41,'transit_server_type_42':42,'transit_server_type_43':43,'transit_server_type_44':44,'transit_server_type_45':45,'transit_server_type_46':46,'transit_server_type_47':47,'transit_server_type_48':48,'transit_server_type_49':49,'transit_server_type_50':50,'transit_server_type_51':51,'transit_server_type_52':52,'transit_server_type_53':53,'transit_server_type_54':54})

In [69]:
test_data.transit_server_type=test_data.transit_server_type.map({'transit_server_type_1':1,'transit_server_type_2':2,'transit_server_type_3':3,'transit_server_type_5':5,'transit_server_type_6':6,'transit_server_type_7':7,'transit_server_type_8':8,'transit_server_type_9':9,'transit_server_type_10':10,'transit_server_type_11':11,'transit_server_type_12':12,'transit_server_type_13':13,'transit_server_type_14':14,'transit_server_type_15':15,'transit_server_type_18':18,'transit_server_type_19':19,'transit_server_type_20':20,'transit_server_type_21':21,'transit_server_type_22':22,'transit_server_type_23':23,'transit_server_type_24':24,'transit_server_type_25':25,'transit_server_type_26':26,'transit_server_type_27':27,'transit_server_type_28':28,'transit_server_type_29':29,'transit_server_type_30':30,'transit_server_type_31':31,'transit_server_type_32':32,'transit_server_type_34':34,'transit_server_type_35':35,'transit_server_type_36':36,'transit_server_type_37':37,'transit_server_type_38':38,'transit_server_type_39':39,'transit_server_type_40':40,'transit_server_type_41':41,'transit_server_type_42':42,'transit_server_type_43':43,'transit_server_type_44':44,'transit_server_type_45':45,'transit_server_type_46':46,'transit_server_type_47':47,'transit_server_type_48':48,'transit_server_type_49':49,'transit_server_type_50':50,'transit_server_type_51':51,'transit_server_type_52':52,'transit_server_type_53':53,'transit_server_type_54':54})

# Visualization 


In [ ]:
data.hist()

In [ ]:
## plot below shows the value count of our three target classes and correlation map of our numeric features. 
f, axes = plt.subplots(1, 2, figsize=(16, 6))
sns.countplot(x = data['outage_duration'], ax=axes[0])
sns.heatmap(data.corr(), annot = True, cmap = "Greens", fmt = ".1f", ax=axes[1])

## above correlation map shows us there is some correlation between broadband type and outage duration also between transit server type and outage type .

## below graph showes us relation between broadband type and outage duration . It could be inferred from the graph that broadband type 2 and 8 have more outages followed by broadband type 7,6,4. 

In [ ]:
plt.figure(figsize=(20,16))
sns.countplot(x='broadband_type',hue='outage_duration',data=data, palette='Set1')
plt.title("broadband_type and related outages " , fontsize=17)
plt.xlabel("broadband type", fontsize=15)

In [ ]:
data["transit_server_type"].value_counts().plot(kind="bar")

In [ ]:
data["area_code"].value_counts().head(50).plot(kind="bar")

## following graph below gives us an idea that transit servers 11,13,20 have more outage type 1  whereas in servers - 34,35 there is more outage type 2 


In [ ]:
plt.figure(figsize=(20,16))
sns.countplot(x='transit_server_type',hue='outage_type',data=data, palette='Set1')
plt.title("transit_server_type and related outages " , fontsize=17)
plt.xlabel("transit server type", fontsize=15)

## below graph gives us an idea where transit server types 11,15,20,34,35 are predominant in outage duration 0.
## server types 11,13,15,20,24,54 are predominant in  outage duration 1.
## server types 11,13,15,42,43,44 are predominant in outage duration 2. 

In [ ]:
plt.figure(figsize=(20,16))
sns.countplot(x='transit_server_type',hue='outage_duration',data=data, palette='Set1')
plt.title("transit_server_type and related outages " , fontsize=17)
plt.xlabel("transit server type", fontsize=15)

### below graph shows us area codes and related outage durations 

In [ ]:
sns.set_style('whitegrid')
sns.countplot(x='outage_duration',hue='area_code',data=data,palette='rainbow')

In [ ]:
plt.figure(figsize=(20,16))
sns.countplot(x='transit_server_type',hue='broadband_type',data=data, palette='Set1')
plt.title("transit_server_type and broadband " , fontsize=17)
plt.xlabel("transit server type", fontsize=15)

## above graph shows us broadband type 2 and 8 are dominant in server types 11 and 15 and 34 and 35. From graphs inferred above we saw broadband 2 and 8 were ADSL type. 

## droping "id" column 

In [116]:

test_data.drop(columns = ["log_report_type"], axis = 1, inplace = True)

In [117]:
test_data.head(5)

volume  broadband_type  transit_server_type  outage_type  area_code  \
0       7.0             8.0                 15.0          2.0          0   
149     7.0             8.0                 15.0          2.0          0   
298     1.0             2.0                 34.0          2.0          1   
361     1.0             2.0                 34.0          2.0          1   
424     1.0             2.0                 34.0          2.0          1   

      id_y  
0     8148  
149   2250  
298   3331  
361   6474  
424  15850

# Separating our dependant and independant variables.

In [94]:
X = data.drop('outage_duration', axis = 1)
y = data['outage_duration']

In [95]:
data.dtypes

log_report_type        int16
volume                 int64
broadband_type         int64
transit_server_type    int64
outage_type            int64
area_code              int16
outage_duration        int64
dtype: object

In [114]:
test_data.dtypes

log_report_type           int8
volume                 float64
broadband_type         float64
transit_server_type    float64
outage_type            float64
area_code                int16
id_y                     int64
dtype: object

In [97]:
X.shape

(48973, 6)

In [98]:
y.shape

(48973,)

# Train Test Split

In [99]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 123)

In [100]:
X_train.shape

(34281, 6)

In [101]:
X_test.shape

(14692, 6)

In [102]:
y_train.shape

(34281,)

In [103]:
y_test.shape

(14692,)

# Model building and evaluation

In [104]:
from sklearn.model_selection import GridSearchCV

def model_building(X, y, test, model, params = None, k = 1) :
    
    if params == None :
        model.fit(X, y)
        
        # return fitted model & train-test predictions
        return (model, model.predict(X), model.predict(test))
    
    else :
        model_cv = GridSearchCV(model, param_grid = params, cv = k)
        model_cv.fit(X, y)
        model = model_cv
        
        
        # return and extra object for all cross validation operations
        return (model_cv, model, model.predict(X), model.predict(test))

In [105]:
from sklearn.metrics import confusion_matrix 
from sklearn.metrics import accuracy_score 
from sklearn.metrics import classification_report 
from sklearn.metrics import f1_score

def model_evaluation(y_train, pred_train, y_test, pred_test) :
    
    print('''
            =========================================
               CLASSIFICATION REPORT FOR TRAIN DATA
            =========================================''')
    print(classification_report(y_train, pred_train))
    print("f1_score: ",f1_score(y_train,pred_train, average= "macro")) 
    print('\nConfusion Matrix :')
    print(confusion_matrix(y_test, pred_test) ) 
    print('\nAccuracy Score :', accuracy_score(y_test, pred_test)) 
    
    
    print('''
            =========================================
               CLASSIFICATION REPORT FOR TEST DATA
            =========================================''')
    print(classification_report(y_test, pred_test))
    print("f1_score: ",f1_score(y_test,pred_test, average = "macro" ))
    print('\nConfusion Matrix :')
    print(confusion_matrix(y_test, pred_test) ) 
    print('\nAccuracy Score :', accuracy_score(y_test, pred_test)) 

## logistic regression

In [106]:
from sklearn.linear_model import LogisticRegression

model, pred_train, pred_test = model_building(X_train, y_train, X_test, LogisticRegression())

In [107]:
model_evaluation(y_train, pred_train, y_test, pred_test)


               CLASSIFICATION REPORT FOR TRAIN DATA
             precision    recall  f1-score   support

          0       0.63      0.88      0.74     20538
          1       0.39      0.24      0.30      8987
          2       0.39      0.01      0.03      4756

avg / total       0.54      0.59      0.52     34281

f1_score:  0.3546729616471343

Confusion Matrix :
[[7681 1097   31]
 [2874  943    8]
 [1600  431   27]]

Accuracy Score : 0.5888238497141302

               CLASSIFICATION REPORT FOR TEST DATA
             precision    recall  f1-score   support

          0       0.63      0.87      0.73      8809
          1       0.38      0.25      0.30      3825
          2       0.41      0.01      0.03      2058

avg / total       0.54      0.59      0.52     14692

f1_score:  0.35258633527298383

Confusion Matrix :
[[7681 1097   31]
 [2874  943    8]
 [1600  431   27]]

Accuracy Score : 0.5888238497141302


## Bagging classifier

In [108]:
from sklearn.ensemble import BaggingClassifier
model1, pred_train, pred_val = model_building(X_train, y_train, X_test, BaggingClassifier())

In [109]:
 model_evaluation(y_train, pred_train, y_test, pred_test)


               CLASSIFICATION REPORT FOR TRAIN DATA
             precision    recall  f1-score   support

          0       0.96      0.97      0.96     20538
          1       0.92      0.91      0.91      8987
          2       0.93      0.92      0.93      4756

avg / total       0.94      0.94      0.94     34281

f1_score:  0.9334001487402445

Confusion Matrix :
[[7681 1097   31]
 [2874  943    8]
 [1600  431   27]]

Accuracy Score : 0.5888238497141302

               CLASSIFICATION REPORT FOR TEST DATA
             precision    recall  f1-score   support

          0       0.63      0.87      0.73      8809
          1       0.38      0.25      0.30      3825
          2       0.41      0.01      0.03      2058

avg / total       0.54      0.59      0.52     14692

f1_score:  0.35258633527298383

Confusion Matrix :
[[7681 1097   31]
 [2874  943    8]
 [1600  431   27]]

Accuracy Score : 0.5888238497141302


## DecisionTree Classifier 

In [110]:
from sklearn.ensemble import RandomForestClassifier

model, pred_train, pred_test = model_building(X_train, y_train, X_test, RandomForestClassifier())
model_evaluation(y_train, pred_train, y_test, pred_test)


               CLASSIFICATION REPORT FOR TRAIN DATA
             precision    recall  f1-score   support

          0       0.96      0.96      0.96     20538
          1       0.91      0.90      0.91      8987
          2       0.93      0.91      0.92      4756

avg / total       0.94      0.94      0.94     34281

f1_score:  0.9293429783309457

Confusion Matrix :
[[7564  972  273]
 [1196 2323  306]
 [ 391  324 1343]]

Accuracy Score : 0.7643615573101007

               CLASSIFICATION REPORT FOR TEST DATA
             precision    recall  f1-score   support

          0       0.83      0.86      0.84      8809
          1       0.64      0.61      0.62      3825
          2       0.70      0.65      0.67      2058

avg / total       0.76      0.76      0.76     14692

f1_score:  0.7137724812507654

Confusion Matrix :
[[7564  972  273]
 [1196 2323  306]
 [ 391  324 1343]]

Accuracy Score : 0.7643615573101007


In [118]:
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
classifier.fit(X_train, y_train)

DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=0,
            splitter='best')

In [119]:
output = classifier.predict(test_data)
output

array([2, 2, 1, ..., 0, 0, 0], dtype=int64)

In [120]:
  output = pd.DataFrame({
        "id": test1,
        "outage_duration": output
    })

output.to_csv('test1.csv', index=False)

In [121]:
output

id  outage_duration
0      3340                2
1     14067                2
2      1134                1
3        27                1
4      9793                1
5     12010                1
6      7213                1
7     16347                0
8      8811                0
9     17705                0
10     7886                0
11     2722                0
12    17659                0
13     7518                0
14     7423                0
15     6174                0
16     8504                0
17    15199                0
18     4403                0
19     3778                0
20    13341                0
21     3271                0
22    11125                0
23    11786                0
24     8572                0
25    14129                0
26    18375                0
27     3711                1
28     4750                1
29     9510                1
...     ...              ...
1447    583                0
1448  14505                0
1449  18193                0
1450  11992                0
1451  10455                0
1452   9132                0
1453  14611                0
1454   4552                0
1455   8564                0
1456   2857                0
1457   3122                0
1458  15017                0
1459  14009                0
1460   1378                0
1461  10752                0
1462   6551                0
1463  11311                0
1464   8099                0
1465   5464                0
1466  14735                0
1467   7221                0
1468  13377                0
1469  15505                0
1470   1967                0
1471   8582                0
1472   7975                0
1473  10664                0
1474   7753                0
1475    989                0
1476   3129                0

[1477 rows x 2 columns]

In [122]:
output[['id','outage_duration']].to_csv(r'C:\Users\LENOVO PC\Desktop\aman\phd\data\output.csv',index=False)